version: '3.8'

services:
  java-app:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: kafka-java-app
    environment:
      - BOOTSTRAP_SERVER_URL=${BOOTSTRAP_SERVER_URL}
      - CONFLUENT_CLUSTER_API_KEY=${CONFLUENT_CLUSTER_API_KEY}
      - CONFLUENT_CLUSTER_API_SECRET=${CONFLUENT_CLUSTER_API_SECRET}
    # command: ["/bin/bash", "-c"]
    command: tail -f /dev/null
    networks:
      - kafka-tutorial-network

  spring-boot-app:
    build:
      context: ./spring-boot
      dockerfile: Dockerfile
    container_name: kafka-spring-boot-app
    environment:
      - BOOTSTRAP_SERVER_URL=${BOOTSTRAP_SERVER_URL}
      - CONFLUENT_CLUSTER_API_KEY=${CONFLUENT_CLUSTER_API_KEY}
      - CONFLUENT_CLUSTER_API_SECRET=${CONFLUENT_CLUSTER_API_SECRET}
    ports:
      - "8080:8080"
    # command: ["/bin/bash", "-c"]
    command: tail -f /dev/null
    networks:
      - kafka-tutorial-network

  python-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: kafka-python-app
    environment:
      - BOOTSTRAP_SERVER_URL=${BOOTSTRAP_SERVER_URL}
      - CONFLUENT_CLUSTER_API_KEY=${CONFLUENT_CLUSTER_API_KEY}
      - CONFLUENT_CLUSTER_API_SECRET=${CONFLUENT_CLUSTER_API_SECRET}
    # command: ["/bin/bash", "-c"]
    command: tail -f /dev/null
    networks:
      - kafka-tutorial-network

  golang-app:
    build:
      context: ./golang
      dockerfile: Dockerfile
    container_name: kafka-golang-app
    environment:
      - BOOTSTRAP_SERVER_URL=${BOOTSTRAP_SERVER_URL}
      - CONFLUENT_CLUSTER_API_KEY=${CONFLUENT_CLUSTER_API_KEY}
      - CONFLUENT_CLUSTER_API_SECRET=${CONFLUENT_CLUSTER_API_SECRET}
    # command: ["/bin/bash", "-c"]
    command: tail -f /dev/null
    networks:
      - kafka-tutorial-network

  nodejs-app:
    build:
      context: ./nodeJS
      dockerfile: Dockerfile
    container_name: kafka-nodejs-app
    environment:
      - BOOTSTRAP_SERVER_URL=${BOOTSTRAP_SERVER_URL}
      - CONFLUENT_CLUSTER_API_KEY=${CONFLUENT_CLUSTER_API_KEY}
      - CONFLUENT_CLUSTER_API_SECRET=${CONFLUENT_CLUSTER_API_SECRET}
    # command: ["/bin/bash", "-c"]
    command: tail -f /dev/null
    networks:
      - kafka-tutorial-network

networks:
  kafka-tutorial-network:
